fix: wrapped where param in db query
VirtusLab-Open-Source/strapi-plugin-comments pull request #152
Opened 2022-07-18 08:35 UTC by ltsNotMike

## Ticket

NA

## Summary

Fixed all query params by wrapping them in objects. 
Fixed minor spelling error. 
Improved type of params in CommonService.FindOne()

## Test Plan

- Test `POST` request to `/:relation`

2022-07-19 09:09 UTC, kamilszewczyk0 reviewed
looks good

2022-07-19 14:54 UTC, CodeVoyager approved these changes

2022-07-27 07:01 UTC, cyp3rius requested changes
@ltsNotMike update please docker image in `circleci` config.

Based on `https://circleci.com/developer/images/image/cimg/node` that should be `cimg/node:14.19.3`

2022-07-27 07:20 UTC, cyp3rius approved these changes

2022-07-27 07:20 UTC, merged