Dashboard page
VirtusLab-Open-Source/strapi-plugin-comments pull request #184
Opened 2023-01-07 21:13 UTC by mkmak2

## Ticket
Dashboard Page

## Summary

to do: 
show how many unread comments u have,
fix page display in navbar,
clean code

2023-01-19 16:01 UTC, CodeVoyager commented on admin/src/pages/DashboardPage/components/LatestComments/index.tsx
> +
Same

2023-01-19 16:01 UTC, CodeVoyager commented on admin/src/pages/DashboardPage/components/LatestComments/index.tsx
> +  const isLoading = isLoadingForData || isFetching;
```suggestion
  const isLoading = isLoadingForData || isFetching || isLoadingForPermissions;
```

To make compound flag, well, compound and in one place.

2023-11-25 15:24 UTC, kamilszewczyk0 requested changes
I cannot display comments, neither on dashboard, nor discover. Also, error on toast is translate key, not string with error message ;/

2023-11-25 15:24 UTC, kamilszewczyk0 commented on admin/src/pages/DashboardPage/components/LatestReports/index.tsx
> +
please do not leave more than 1 empty line of space

2023-11-25 15:24 UTC, kamilszewczyk0 commented on admin/src/pages/Discover/components/DiscoverTableRow/index.tsx
unnecessary empty space

2023-11-25 15:24 UTC, kamilszewczyk0 commented on admin/src/pages/Reports/index.tsx
>    const {
please leave just one line of space

2023-11-25 15:24 UTC, kamilszewczyk0 commented on server/controllers/admin.ts
> +
unnecessary empty line

2025-08-03 12:58 UTC, closed without merging