feat: author entity props blocking
VirtusLab-Open-Source/strapi-plugin-comments pull request #186
Opened 2023-01-31 14:41 UTC by CodeVoyager

## Ticket

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/183

## Summary

What does this PR do/solve?

- removing selected fields from author object in the response by config
- minor UI issue

## Test Plan

- set `blockedAuthorProps` in config
- query for comments
- blocked props should be blocked

2023-01-31 16:24 UTC, kamilszewczyk0 requested changes

2023-01-31 16:24 UTC, kamilszewczyk0 commented on admin/src/components/Avatar/index.tsx
> +  avatar: string | ToBeFixed;
unnecessary repetitions

2023-02-01 07:41 UTC, cyp3rius approved these changes

2023-02-01 14:37 UTC, Jahorse commented
I tried pulling the PR locally and building it into my website. I added `blockedAuthorProps: ['email'],` to my `plugins.js` file, but I can still see the email field on the front end. 

When debugging the code, I see it isn't finding the `blockedAuthorProps` key in my config. It looks like it's only finding the config values I have set inside my admin panel and skipping the local config. This seems to be happening because the `useLocal` parameter defaults to `false` here: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/blob/master/server/services/common.ts#L61. When I override this value to `true` I am able to get the functionality I expect, the email field is not returned.

2023-02-02 12:00 UTC, Jahorse commented
@cyp3rius I did use the restore feature after setting the new config field. Is this new field integrated with that restore functionality properly? It didn't seem to do anything for me. If I get time later I'll try to run a restore through the debugger to confirm.

2023-02-02 15:16 UTC, CodeVoyager commented
I added a new input for the settings page. From now on you don't need to put settings in the file.

2023-02-03 23:04 UTC, Jahorse commented
I pulled in the latest updates and everything is working great! I was able to use the reset button from the admin panel and it reset the blocked props field to the value from my plugins config. Calling the comments plugin API from my frontend did not return the email field.

2023-02-06 16:10 UTC, cyp3rius approved these changes

2023-02-06 16:11 UTC, merged